version: '3'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    image: openjdk:21-jdk-slim
    container_name: moon-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db # todo: replace 
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: node:24-alpine3.20
    container_name: vue-frontend
    volumes:
      - ./moon-colonization:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # TODO: to release
    ports:
      - "5173:5173"
    networks:
      - app-network

  site:
    image: node:24-alpine3.20
    container_name: vue-site
    volumes:
      - ./moon-site:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # TODO: to release
    ports:
      - "5174:5174"
    networks:
      - app-network

  docs:
    image: node:24-alpine3.20
    container_name: vue-docs
    volumes:
        - ./docs:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # TODO: to release
    ports:
      - "5175:5175"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge